const $=s=>document.querySelector(s);
let DATA={evento:{},trabajos:[],mesas:[],programaGeneral:[]},view='inicio';
let filters={q:'',day:'all',mesa:'all',modalidad:'all',tipo:'all'};
const KEY='iceaAgenda2026';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc=(s='')=>String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
async function boot(){try{const r=await fetch('data/programa.json?v=20260921-ajustes-autores-pon18',{cache:'no-store'});if(!r.ok)throw Error('No se pudo cargar el programa maestro');const master=await r.json();const mesas=[...new Set((master.trabajos||[]).map(t=>t.mesa).filter(Boolean))].map(codigo=>({codigo}));DATA={evento:master.evento||{},programaGeneral:master.programaGeneral||[],trabajos:master.trabajos||[],mesas};bind();render();countdown()}catch(e){$('#app').innerHTML=`<div class="error"><b>No se pudo cargar el programa.</b><br>${esc(e.message)}</div>`}}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=closeMenu;$('#closeDialog').onclick=()=>$('#dialog').close();$('#globalSearch').oninput=e=>{filters.q=e.target.value;filters.day='all';view='programa';setNav('programa');render()}}
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')} function setNav(v){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v))} function go(v){view=v;setNav(v);closeMenu();render();scrollTo({top:0,behavior:'smooth'})} function render(){const a=$('#app');a.innerHTML=view==='inicio'?inicio():view==='programa'?programa():view==='agenda'?agenda():constancias();updateCount()}
function inicio(){const t=DATA.evento.totales||{};const hi=highlights();return `<section class="hero"><img class="hero-logo" src="assets/logos/logo-congreso.png" alt="Logo del Congreso"></section><section class="intro-strip"><div class="metric"><div id="countdown" class="countdown"></div></div><div class="metric"><b>${t.trabajos}</b><span>Trabajos</span></div><div class="metric"><b>${t.ponencias}</b><span>Ponencias</span></div><div class="metric"><b>${t.carteles}</b><span>Carteles</span></div></section><div class="section-head"><div><div class="eyebrow">Imperdibles</div><h2 class="section-title">Momentos centrales del Congreso</h2></div><button class="text-link" onclick="filters.day='all';go('programa')">Ver programa completo →</button></div><section class="highlights">${hi.map(highlightCard).join('')}</section><section class="home-map"><div class="home-map-copy"><div class="eyebrow">Orientación</div><h2>Croquis de la sede</h2><p>Consulta la ubicación de los espacios del ICEA durante el Congreso.</p></div><img src="assets/images/croquis-icea.png" alt="Croquis ICEA"></section>`}
function highlights(){return DATA.programaGeneral.filter(e=>/registro de ponentes|inaugur|conferencia magistral|foro de expertos|foro de turismo|clausura|encuentro de cierre|expo empresarial|reunión anual/i.test(e.actividad||''))} function zoomAction(e){if(e.modalidad!=='Virtual')return '';return e.zoom?`<a class="chip-btn" href="${esc(e.zoom)}" target="_blank" rel="noopener">Entrar a la sesión</a>`:`<button class="chip-btn zoom-pending" type="button" disabled>Enlace Zoom pendiente</button>`} function highlightCard(e){const kit=/^registro de ponentes$/i.test(e.actividad||'')?'<p><strong>Entrega de kit: ponentes en modalidad presencial.</strong></p>':'';return `<article class="highlight"><time>${esc(e.fecha)}</time><h3>${esc(e.actividad)}</h3><p>${esc(e.modalidad)} · ${esc(e.ubicacion)}</p><b>${esc(e.horario)}</b>${kit}${zoomAction(e)?`<div class="highlight-action">${zoomAction(e)}</div>`:''}</article>`}
function dayTabs(){return `<div class="day-tabs">${[['all','Vista general','Programa general'],['1','Miércoles','23 de septiembre'],['2','Jueves','24 de septiembre'],['3','Viernes','25 de septiembre']].map(d=>`<button class="day-tab ${filters.day===d[0]?'active':''}" onclick="filters.day='${d[0]}';render()"><span>${d[1]}</span><b>${d[2]}</b></button>`).join('')}</div>`}
function filtered(){const q=norm(filters.q);return DATA.trabajos.filter(t=>{const dayOK=q?true:(filters.day==='all'||String(t.dia)===filters.day);return dayOK&&(filters.mesa==='all'||t.mesa===filters.mesa)&&(filters.modalidad==='all'||t.modalidad===filters.modalidad)&&(filters.tipo==='all'||t.tipo===filters.tipo)&&(!q||norm([t.codigo,t.titulo,(t.autores||[]).join(' '),t.mesa].join(' ')).includes(q))})}
function matchingSpecials(day){const q=norm(filters.q);if(q)return [];return DATA.programaGeneral.filter(e=>(day==='all'||String(e.dia)===String(day))&&!/^(ponencias|carteles)$/i.test(String(e.actividad||'').trim()))}
function programa(){const items=filtered();return `<div class="section-head"><div><div class="eyebrow">Programa académico</div><h1 class="section-title">Programa del Congreso</h1><p class="lead">Consulta el programa general o navega por día. Las participaciones están organizadas por mesa o bloque.</p></div></div>${dayTabs()}<div class="filters simple"><select onchange="filters.mesa=this.value;render()"><option value="all">Todas las mesas / bloques</option>${DATA.mesas.map(m=>`<option value="${esc(m.codigo)}" ${filters.mesa===m.codigo?'selected':''}>${esc(m.codigo)}</option>`).join('')}</select><select onchange="filters.modalidad=this.value;render()"><option value="all">Todas las modalidades</option><option ${filters.modalidad==='Presencial'?'selected':''}>Presencial</option><option ${filters.modalidad==='Virtual'?'selected':''}>Virtual</option></select><select onchange="filters.tipo=this.value;render()"><option value="all">Ponencias y carteles</option><option ${filters.tipo==='Ponencia'?'selected':''}>Ponencia</option><option ${filters.tipo==='Cartel'?'selected':''}>Cartel</option></select></div>${programContent(items)}`}
function programContent(items){const q=norm(filters.q);const days=(q||filters.day==='all')?[1,2,3]:[Number(filters.day)];let html='';for(const d of days){const di=items.filter(x=>x.dia===d);const sp=matchingSpecials(String(d));if(!di.length&&!sp.length)continue;html+=`<div class="program-day"><div class="program-day-head"><span>${22+d}</span><div><b>${22+d} de septiembre</b><small>${d===1?'Miércoles':d===2?'Jueves':'Viernes'}</small></div></div>`;if(sp.length)html+=`<div class="day-specials">${sp.map(specialCompact).join('')}</div>`;const order=[];di.forEach(x=>{const k=x.mesa||x.tipo;if(!order.includes(k))order.push(k)});order.sort((a,b)=>blockOrder(a)-blockOrder(b));html+=`<div class="mesa-stack">${order.map(k=>blockCard(d,k,di.filter(x=>(x.mesa||x.tipo)===k))).join('')}</div></div>`}return html||`<div class="empty">No hay resultados relacionados con la búsqueda.</div>`}
function blockOrder(k){const m=String(k).match(/Mesa (\d)/i);if(m)return Number(m[1]);if(/carteles/i.test(k))return 7;if(/virtual/i.test(k))return 6;return 9}
function specialCompact(e){return `<article class="special-compact"><time>${esc(e.horario)}</time><div><b>${esc(e.actividad)}</b><span>${esc(e.modalidad)} · ${esc(e.ubicacion)}</span>${zoomAction(e)?`<div>${zoomAction(e)}</div>`:''}</div></article>`}
function blockCard(d,k,arr){arr.sort((a,b)=>timeKey(a.horario)-timeKey(b.horario));const first=arr[0], rr=first.roles||{}, virtual=first.modalidad==='Virtual', zoom=first.zoom||'';const times=arr.map(x=>x.horario).filter(Boolean);const range=times.length?`${times[0].split(/[–-]/)[0]}–${times[times.length-1].split(/[–-]/)[1]||times[times.length-1]}`:'';return `<details class="mesa-card" open><summary><div class="mesa-title"><b>${esc(k)}</b><span>${esc(first.tipo)} · ${esc(first.modalidad)}</span></div><div class="mesa-facts"><b>${esc(range)}</b><span>${esc(first.sala)}</span>${virtual&&zoom?`<a class="zoom-link" href="${esc(zoom)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Entrar a la sesión</a>`:''}</div><span class="chev">⌄</span></summary>${rolesHtml(rr,first.notaResponsables)}<div class="mesa-works">${arr.map(workRow).join('')}</div></details>`}
function rolesHtml(r,note){const vals=[r.lider,r.moderador,r.apoyo].filter(x=>x&&x!=='—');if(!vals.length&&!note)return '';return `<div class="roles">${r.lider&&r.lider!=='—'?`<div><span>Líder de mesa</span><b>${esc(r.lider)}</b></div>`:''}${r.moderador&&r.moderador!=='—'?`<div><span>Moderador(a)</span><b>${esc(r.moderador)}</b></div>`:''}${r.apoyo&&r.apoyo!=='—'?`<div><span>Apoyo</span><b>${esc(r.apoyo)}</b></div>`:''}${note?`<div><span>Coordinación de carteles</span><b>${esc(note)}</b></div>`:''}</div>`}
function workRow(t){const s=saved(t.codigo||t.titulo);return `<article class="work-row"><time>${esc(t.horario)}</time><div><h4>${t.codigo?`<span class="code">${esc(t.codigo)}</span> · `:''}${esc(t.titulo)}</h4><p>${(t.autores||[]).map(esc).join('; ')}</p></div><div class="session-actions"><button class="chip-btn ${s?'saved':''}" onclick="toggle('${esc(t.codigo||t.titulo)}')">${s?'★ Guardado':'☆ Mi Agenda'}</button><button class="chip-btn" onclick="detailByTitle(${JSON.stringify(t.titulo)})">Ver detalles</button></div></article>`}
function timeKey(v=''){const m=String(v).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):9999}
function agenda(){const ids=getAgenda(),x=DATA.trabajos.filter(t=>ids.includes(t.codigo||t.titulo));return `<div class="section-head"><div><div class="eyebrow">Mi Agenda</div><h1 class="section-title">Lo que no quieres perderte</h1></div></div>${x.length?`<div class="agenda-list">${x.sort((a,b)=>a.dia-b.dia||timeKey(a.horario)-timeKey(b.horario)).map(t=>`<div class="agenda-day"><b>${esc(t.diaTexto)} · ${esc(t.mesa)}</b>${workRow(t)}</div>`).join('')}</div>`:`<div class="agenda-empty"><h3>Aún no has guardado actividades</h3></div>`}`}
function constancias(){const q=norm(filters.q),x=DATA.trabajos.filter(t=>!q||norm([t.codigo,t.titulo,(t.autores||[]).join(' ')].join(' ')).includes(q));return `<div class="section-head"><div><div class="eyebrow">Constancias</div><h1 class="section-title">Encuentra tu participación</h1><p class="lead">Usa el buscador superior por nombre, título o código.</p></div></div><div class="notice"><b>Disponibilidad de constancias</b><span>Podrán consultarse y descargarse a partir del <b>28 de septiembre de 2026</b>.</span></div><div class="const-list">${x.map(t=>`<article class="const-item"><div class="code">${esc(t.codigo||t.tipo)}</div><div><h4>${esc(t.titulo)}</h4><p>${(t.autores||[]).map(esc).join('; ')}</p></div><div class="session-actions"><button class="chip-btn" onclick="detailByTitle(${JSON.stringify(t.titulo)})">Ver participación</button></div></article>`).join('')}</div>`}
function detailByTitle(title){const t=DATA.trabajos.find(x=>x.titulo===title);if(!t)return;$('#dialogBody').innerHTML=`<div class="dialog-head"><div class="eyebrow">${esc(t.codigo||t.tipo)} · ${esc(t.modalidad)}</div><h2>${esc(t.titulo)}</h2></div><div class="dialog-content"><p><b>Autores:</b> ${(t.autores||[]).map(esc).join('; ')}</p><p><b>Fecha:</b> ${esc(t.diaTexto||((22+Number(t.dia))+' de septiembre'))} · ${esc(t.horario)}<br><b>Mesa / bloque:</b> ${esc(t.mesa)}<br><b>Sede:</b> ${esc(t.sala)}</p>${t.modalidad==='Virtual'&&t.zoom?`<p><a class="zoom-link" href="${esc(t.zoom)}" target="_blank" rel="noopener">Entrar a la sesión</a></p>`:''}</div>`;$('#dialog').showModal()}
function getAgenda(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}} function saved(c){return getAgenda().includes(c)} function toggle(c){const s=new Set(getAgenda());s.has(c)?s.delete(c):s.add(c);localStorage.setItem(KEY,JSON.stringify([...s]));render()} function updateCount(){const e=$('#agendaCount');if(e)e.textContent=getAgenda().length?`(${getAgenda().length})`:''}
function countdown(){function tick(){const e=$('#countdown');if(!e)return;let d=Math.max(0,new Date('2026-09-23T10:00:00-06:00')-Date.now());const vals=[['Días',Math.floor(d/86400000)],['Horas',Math.floor(d%86400000/3600000)],['Min',Math.floor(d%3600000/60000)],['Seg',Math.floor(d%60000/1000)]];e.innerHTML=vals.map(v=>`<div><b>${String(v[1]).padStart(2,'0')}</b><span>${v[0]}</span></div>`).join('')}tick();setInterval(tick,1000)}
boot();