const $=s=>document.querySelector(s);let DATA={trabajos:[],programaGeneral:[],semblanzas:[]},view='inicio';let filters={q:'',day:'all',mesa:'all',modalidad:'all'};const KEY='iceaAgenda2026';const colors={'Mesa 1':'#6f1232','Mesa 2':'#315d8a','Mesa 3':'#087b76','Mesa 4':'#b44843','Mesa 5':'#b17d2d'};
async function boot(){try{const r=await fetch('data/programa.json?v=20260901b',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);DATA=await r.json();bind();render();countdown()}catch(e){$('#app').innerHTML=`<div class="empty"><b>No se pudo cargar el programa.</b><br>${e.message}</div>`}}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=()=>{$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')};$('#closeDialog').onclick=()=>$('#dialog').close();$('#globalSearch').oninput=e=>{filters.q=e.target.value;view='programa';render()}}
function go(v){view=v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show');render();scrollTo(0,0)}
function head(k,t,p){return `<div class="section-head"><div><div class="kicker">${k}</div><h1>${t}</h1><p>${p}</p></div></div>`}
function render(){const a=$('#app');a.innerHTML=view==='inicio'?inicio():view==='cronograma'?cronograma():view==='programa'?programa():view==='agenda'?agenda():view==='eventos'?eventos():view==='semblanzas'?semblanzas():view==='carteles'?carteles():view==='constancias'?constancias():info();updateCount()}
function inicio(){const t=DATA.evento.totales;return `<section class="hero"><div class="eyebrow">Programa oficial · ICEA UAEH</div><h1>Ideas que investigan.<br>Conexiones que transforman.</h1><p>Consulta el programa final, arma tu agenda, conoce a quienes participan y recorre los tres días del 11° Congreso Internacional ICEA 2026.</p><div class="actions"><button class="btn primary" onclick="go('cronograma')">Explorar cronograma</button><button class="btn" onclick="go('programa')">Consultar programa</button></div></section><section class="stats"><div class="stat"><div id="countdown" class="countdown"></div></div><div class="stat"><b>${t.trabajos}</b><span>Trabajos</span></div><div class="stat"><b>${t.ponencias}</b><span>Ponencias</span></div><div class="stat"><b>${t.carteles}</b><span>Carteles</span></div><div class="stat"><b>${t.semblanzas}</b><span>Semblanzas</span></div></section>${head('Tres días · una experiencia','Cronograma del Congreso','Una lectura rápida de lo que ocurre cada día, con los horarios ya actualizados en el programa final.')}${timeline(DATA.programaGeneral)}${head('Encuentros centrales','Eventos destacados','Los momentos plenarios y de encuentro que articulan la experiencia del Congreso.')}${eventCards(DATA.programaGeneral.filter(e=>/inauguración|panel|conferencia|foro|reunión|clausura|brindis/i.test(e.actividad)))}`}
function timeline(items){const days=['23 septiembre','24 septiembre','25 septiembre'];return `<div class="timeline">${days.map((d,i)=>`<section class="day"><div class="day-title"><b>${23+i}</b><span>septiembre · 2026</span></div>${items.filter(e=>e.fecha===d).map(e=>`<div class="timeline-row"><time>${e.horario}</time><div><strong>${e.actividad}</strong>${e.detalle?`<small>${e.detalle}</small>`:''}</div><div class="place">${e.ubicacion||''}</div></div>`).join('')}</section>`).join('')}</div>`}
function cronograma(){return head('Programa general','Cronograma completo','Consulta la secuencia general de actividades del 23 al 25 de septiembre. Los horarios corresponden al archivo final proporcionado.')+timeline(DATA.programaGeneral)}
function tabs(){return `<div class="tabs">${[['all','Todos'],['1','23 sep'],['2','24 sep'],['3','25 sep']].map(x=>`<button class="tab ${filters.day===x[0]?'active':''}" onclick="filters.day='${x[0]}';render()">${x[1]}</button>`).join('')}</div>`}
function toolbar(){const mesas=[...new Set(DATA.trabajos.map(x=>x.mesa).filter(Boolean))].sort();return `${tabs()}<div class="toolbar"><input value="${esc(filters.q)}" placeholder="Título, autor o código…" oninput="filters.q=this.value;render()"><select onchange="filters.mesa=this.value;render()"><option value="all">Todas las mesas</option>${mesas.map(m=>`<option ${filters.mesa===m?'selected':''}>${m}</option>`).join('')}</select><select onchange="filters.modalidad=this.value;render()"><option value="all">Todas las modalidades</option><option ${filters.modalidad==='Presencial'?'selected':''}>Presencial</option><option ${filters.modalidad==='Virtual'?'selected':''}>Virtual</option></select></div>`}
function filtered(type){const q=filters.q.toLowerCase().trim();return DATA.trabajos.filter(t=>(!type||t.tipo===type)&&(filters.day==='all'||String(t.dia)===filters.day)&&(filters.mesa==='all'||t.mesa===filters.mesa)&&(filters.modalidad==='all'||t.modalidad===filters.modalidad)&&(!q||[t.codigo,t.titulo,(t.autores||[]).join(' '),t.mesa,t.sala].join(' ').toLowerCase().includes(q)))}
function card(t){const s=saved(t.codigo);return `<article class="card" style="--mesa:${colors[t.mesa]||'#6f1232'}"><div class="meta">${t.codigo} · ${t.tipo} · ${t.modalidad}</div><h3>${t.titulo}</h3><p><b>${t.autores.join('; ')}</b><br>${t.diaTexto} · ${t.horario}<br>${t.mesa} · ${t.sala||''}</p><div class="actions"><button class="small ${s?'saved':''}" onclick="toggle('${t.codigo}')">${s?'Guardado':'Mi Agenda'}</button><button class="small" onclick="detail('${t.codigo}')">Ver información</button>${t.semblanza?`<button class="small" onclick="bioByWork('${t.codigo}')">Semblanza</button>`:''}</div></article>`}
function cards(x){return x.length?`<div class="grid">${x.map(card).join('')}</div>`:`<div class="empty">No hay resultados con esos filtros.</div>`}
function programa(){return head('Programa académico','Encuentra tu participación','Filtra por día, mesa o modalidad. Los horarios y sedes provienen del programa final actualizado.')+toolbar()+cards(filtered())}
function carteles(){return head('Presentación de carteles','Carteles científicos','Consulta los 20 carteles presenciales y los 6 carteles virtuales del Congreso.')+toolbar()+cards(filtered('Cartel'))}
function agenda(){const ids=getAgenda(),x=DATA.trabajos.filter(t=>ids.includes(t.codigo));return head('Selección personal','Mi Agenda','Guarda las participaciones que quieres seguir. La selección permanece en este navegador.')+(x.length?cards(x):`<div class="empty">Todavía no has guardado actividades. Entra al Programa y selecciona “Mi Agenda”.</div>`)}
function eventos(){return head('Programa general','Eventos destacados','Ceremonias, panel, conferencia magistral, foro, reunión anual y brindis de cierre.')+eventCards(DATA.programaGeneral.filter(e=>/inauguración|panel|conferencia|foro|reunión|clausura|brindis/i.test(e.actividad)))}
function eventCards(x){return `<div class="event-grid">${x.map(e=>`<article class="event"><div><div class="kicker">${e.fecha}</div><h3>${e.actividad}</h3><p>${e.ubicacion||''}</p></div><time>${e.horario||''}</time></article>`).join('')}</div>`}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function semblanzas(){const q=filters.q.toLowerCase().trim(),x=DATA.semblanzas.filter(s=>!q||[s.nombre,s.semblanza,(s.participaciones||[]).map(p=>p.titulo).join(' ')].join(' ').toLowerCase().includes(q));return head('Personas y trayectorias','Semblanzas','Conoce la trayectoria académica y profesional de quienes proporcionaron semblanza para el Congreso.')+`<div class="toolbar" style="grid-template-columns:1fr"><input value="${esc(filters.q)}" placeholder="Buscar por nombre o tema…" oninput="filters.q=this.value;render()"></div>`+(x.length?`<div class="profiles">${x.map((s,i)=>`<article class="profile"><div class="avatar">${initials(s.nombre)}</div><h3>${s.nombre}</h3><p>${s.semblanza}</p><button class="small" onclick="bio(${i},'${escAttr(s.nombre)}')">Leer semblanza completa</button></article>`).join('')}</div>`:`<div class="empty">No encontramos una semblanza con esa búsqueda.</div>`)}
function bio(i,name){const s=DATA.semblanzas.find(x=>x.nombre===name);if(!s)return;$('#dialogBody').innerHTML=`<div class="dialog-body"><div class="kicker">Semblanza</div><h2>${s.nombre}</h2><p class="bio">${s.semblanza}</p>${s.participaciones?.length?`<div class="notice"><b>Participación en el Congreso</b><br>${s.participaciones.map(p=>`${p.titulo} · ${p.dia} · ${p.horario}`).join('<br><br>')}</div>`:''}</div>`;$('#dialog').showModal()}
function bioByWork(code){const t=DATA.trabajos.find(x=>x.codigo===code);if(!t||!t.semblanza)return;const s=DATA.semblanzas.find(x=>x.semblanza===t.semblanza);if(s)bio(0,s.nombre)}
function constancias(){const q=filters.q.toLowerCase().trim(),x=DATA.trabajos.filter(t=>!q||[t.codigo,t.titulo,t.autores.join(' ')].join(' ').toLowerCase().includes(q));return head('Consulta por participación','Constancias','Localiza tu trabajo. Los botones de descarga se activarán cuando los PDF sean incorporados al repositorio.')+`<div class="toolbar" style="grid-template-columns:1fr"><input value="${esc(filters.q)}" placeholder="Nombre, título o código…" oninput="filters.q=this.value;render()"></div>`+cards(x)}
function info(){return head('Sede y orientación','Información para asistentes','Datos básicos para ubicarte y aprovechar la plataforma durante el Congreso.')+`<div class="info-grid"><div class="panel"><div class="kicker">Sede</div><h2>ICEA · UAEH</h2><p>Instituto de Ciencias Económico-Administrativas · San Agustín Tlaxiaca, Hidalgo.</p><p><b>Fechas:</b> 23, 24 y 25 de septiembre de 2026.<br><b>Modalidad:</b> presencial y virtual.</p></div><div class="panel"><div class="kicker">Cómo usar el sitio</div><h2>Tu ruta en el Congreso</h2><p>Revisa primero el Cronograma; después usa Programa para buscar por título, autor, mesa o modalidad. Guarda tus actividades en Mi Agenda y consulta las Semblanzas sin salir del sitio.</p><div class="notice">Carteles y constancias podrán vincularse por código conforme se incorporen los PDF.</div></div></div>`}
function detail(code){const t=DATA.trabajos.find(x=>x.codigo===code);if(!t)return;$('#dialogBody').innerHTML=`<div class="dialog-body"><div class="kicker">${t.codigo} · ${t.tipo} · ${t.modalidad}</div><h2>${t.titulo}</h2><p><b>Autores:</b> ${t.autores.join('; ')}</p><p><b>Fecha y hora:</b> ${t.diaTexto} · ${t.horario}<br><b>Mesa:</b> ${t.mesa}${t.mesaNombre?' · '+t.mesaNombre.replace(/^Mesa \d+\.\s*/,''):''}<br><b>Sede:</b> ${t.sala||'Por confirmar'}</p><div class="actions"><button class="small ${saved(t.codigo)?'saved':''}" onclick="toggle('${t.codigo}');detail('${t.codigo}')">${saved(t.codigo)?'Guardado en Mi Agenda':'Agregar a Mi Agenda'}</button>${t.semblanza?`<button class="small" onclick="bioByWork('${t.codigo}')">Leer semblanza</button>`:''}</div></div>`;$('#dialog').showModal()}
function getAgenda(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function saved(c){return getAgenda().includes(c)}function toggle(c){const s=new Set(getAgenda());s.has(c)?s.delete(c):s.add(c);localStorage.setItem(KEY,JSON.stringify([...s]));render()}function updateCount(){const e=$('#agendaCount');if(e)e.textContent=getAgenda().length?`(${getAgenda().length})`:''}
function countdown(){function tick(){const e=$('#countdown');if(!e)return;let d=Math.max(0,new Date('2026-09-23T10:00:00-06:00')-Date.now());const v=[['Días',Math.floor(d/86400000)],['Horas',Math.floor(d%86400000/3600000)],['Min',Math.floor(d%3600000/60000)],['Seg',Math.floor(d%60000/1000)]];e.innerHTML=v.map(x=>`<div><b>${String(x[1]).padStart(2,'0')}</b><span>${x[0]}</span></div>`).join('')}tick();setInterval(tick,1000)}
function esc(s=''){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}function escAttr(s=''){return String(s).replace(/'/g,"\\'")};boot();
